version: "3.9"
services:
  nginx-api-gateway-se356-be:
    image: nginx:alpine
    container_name: nginx-api-gateway-se356-be
    ports:
      - "9607:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
